// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: room_actor.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressRequest) Reset() {
	*x = ProgressRequest{}
	mi := &file_room_actor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressRequest) ProtoMessage() {}

func (x *ProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_actor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressRequest.ProtoReflect.Descriptor instead.
func (*ProgressRequest) Descriptor() ([]byte, []int) {
	return file_room_actor_proto_rawDescGZIP(), []int{0}
}

func (x *ProgressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProgressRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ProgressRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ProgressResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Message        string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	State          string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	ActiveMessages int64                  `protobuf:"varint,3,opt,name=ActiveMessages,proto3" json:"ActiveMessages,omitempty"` // Currently active messages being processed
	LastActivity   int64                  `protobuf:"varint,4,opt,name=LastActivity,proto3" json:"LastActivity,omitempty"`     // Last activity timestamp in UnixNano
	ProcessingTime int64                  `protobuf:"varint,5,opt,name=ProcessingTime,proto3" json:"ProcessingTime,omitempty"` // Total processing time in nanoseconds
	MessageCount   int64                  `protobuf:"varint,6,opt,name=MessageCount,proto3" json:"MessageCount,omitempty"`     // Total messages processed
	ErrorCount     int64                  `protobuf:"varint,7,opt,name=ErrorCount,proto3" json:"ErrorCount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProgressResponse) Reset() {
	*x = ProgressResponse{}
	mi := &file_room_actor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressResponse) ProtoMessage() {}

func (x *ProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_actor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressResponse.ProtoReflect.Descriptor instead.
func (*ProgressResponse) Descriptor() ([]byte, []int) {
	return file_room_actor_proto_rawDescGZIP(), []int{1}
}

func (x *ProgressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProgressResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ProgressResponse) GetActiveMessages() int64 {
	if x != nil {
		return x.ActiveMessages
	}
	return 0
}

func (x *ProgressResponse) GetLastActivity() int64 {
	if x != nil {
		return x.LastActivity
	}
	return 0
}

func (x *ProgressResponse) GetProcessingTime() int64 {
	if x != nil {
		return x.ProcessingTime
	}
	return 0
}

func (x *ProgressResponse) GetMessageCount() int64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *ProgressResponse) GetErrorCount() int64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

type WorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QId           string                 `protobuf:"bytes,1,opt,name=qId,proto3" json:"qId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkRequest) Reset() {
	*x = WorkRequest{}
	mi := &file_room_actor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkRequest) ProtoMessage() {}

func (x *WorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_actor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkRequest.ProtoReflect.Descriptor instead.
func (*WorkRequest) Descriptor() ([]byte, []int) {
	return file_room_actor_proto_rawDescGZIP(), []int{2}
}

func (x *WorkRequest) GetQId() string {
	if x != nil {
		return x.QId
	}
	return ""
}

type StopProcessor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopProcessor) Reset() {
	*x = StopProcessor{}
	mi := &file_room_actor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProcessor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProcessor) ProtoMessage() {}

func (x *StopProcessor) ProtoReflect() protoreflect.Message {
	mi := &file_room_actor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProcessor.ProtoReflect.Descriptor instead.
func (*StopProcessor) Descriptor() ([]byte, []int) {
	return file_room_actor_proto_rawDescGZIP(), []int{3}
}

func (x *StopProcessor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_room_actor_proto protoreflect.FileDescriptor

const file_room_actor_proto_rawDesc = "" +
	"\n" +
	"\x10room_actor.proto\x12\x05actor\"\xba\x01\n" +
	"\x0fProgressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\bmetadata\x18\x02 \x03(\v2$.actor.ProgressRequest.MetadataEntryR\bmetadata\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfa\x01\n" +
	"\x10ProgressResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12&\n" +
	"\x0eActiveMessages\x18\x03 \x01(\x03R\x0eActiveMessages\x12\"\n" +
	"\fLastActivity\x18\x04 \x01(\x03R\fLastActivity\x12&\n" +
	"\x0eProcessingTime\x18\x05 \x01(\x03R\x0eProcessingTime\x12\"\n" +
	"\fMessageCount\x18\x06 \x01(\x03R\fMessageCount\x12\x1e\n" +
	"\n" +
	"ErrorCount\x18\a \x01(\x03R\n" +
	"ErrorCount\"\x1f\n" +
	"\vWorkRequest\x12\x10\n" +
	"\x03qId\x18\x01 \x01(\tR\x03qId\"\x1f\n" +
	"\rStopProcessor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2T\n" +
	"\x13SequentialProcessor\x12=\n" +
	"\bProgress\x12\x16.actor.ProgressRequest\x1a\x17.actor.ProgressResponse\"\x00B|\n" +
	"\tcom.actorB\x0eRoomActorProtoP\x01Z+github.com/antinvestor/matrix/apis/actor/v1\xa2\x02\x03AXX\xaa\x02\x05Actor\xca\x02\x05Actor\xe2\x02\x11Actor\\GPBMetadata\xea\x02\x05Actorb\x06proto3"

var (
	file_room_actor_proto_rawDescOnce sync.Once
	file_room_actor_proto_rawDescData []byte
)

func file_room_actor_proto_rawDescGZIP() []byte {
	file_room_actor_proto_rawDescOnce.Do(func() {
		file_room_actor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_actor_proto_rawDesc), len(file_room_actor_proto_rawDesc)))
	})
	return file_room_actor_proto_rawDescData
}

var file_room_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_room_actor_proto_goTypes = []any{
	(*ProgressRequest)(nil),  // 0: actor.ProgressRequest
	(*ProgressResponse)(nil), // 1: actor.ProgressResponse
	(*WorkRequest)(nil),      // 2: actor.WorkRequest
	(*StopProcessor)(nil),    // 3: actor.StopProcessor
	nil,                      // 4: actor.ProgressRequest.MetadataEntry
}
var file_room_actor_proto_depIdxs = []int32{
	4, // 0: actor.ProgressRequest.metadata:type_name -> actor.ProgressRequest.MetadataEntry
	0, // 1: actor.SequentialProcessor.Progress:input_type -> actor.ProgressRequest
	1, // 2: actor.SequentialProcessor.Progress:output_type -> actor.ProgressResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_room_actor_proto_init() }
func file_room_actor_proto_init() {
	if File_room_actor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_actor_proto_rawDesc), len(file_room_actor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_actor_proto_goTypes,
		DependencyIndexes: file_room_actor_proto_depIdxs,
		MessageInfos:      file_room_actor_proto_msgTypes,
	}.Build()
	File_room_actor_proto = out.File
	file_room_actor_proto_goTypes = nil
	file_room_actor_proto_depIdxs = nil
}
