// Code generated by protoc-gen-grain. DO NOT EDIT.
// versions:
//  protoc-gen-grain v0.7.0
//  protoc           (unknown)
// source: room_actor.proto

package v1

import (
	fmt "fmt"
	actor "github.com/asynkron/protoactor-go/actor"
	cluster "github.com/asynkron/protoactor-go/cluster"
	proto "google.golang.org/protobuf/proto"
	slog "log/slog"
	time "time"
)

var xRoomEventProcessorFactory func() RoomEventProcessor

// RoomEventProcessorFactory produces a RoomEventProcessor
func RoomEventProcessorFactory(factory func() RoomEventProcessor) {
	xRoomEventProcessorFactory = factory
}

// GetRoomEventProcessorGrainClient instantiates a new RoomEventProcessorGrainClient with given Identity
func GetRoomEventProcessorGrainClient(c *cluster.Cluster, id string) *RoomEventProcessorGrainClient {
	if c == nil {
		panic(fmt.Errorf("nil cluster instance"))
	}
	if id == "" {
		panic(fmt.Errorf("empty id"))
	}
	return &RoomEventProcessorGrainClient{Identity: id, cluster: c}
}

// GetRoomEventProcessorKind instantiates a new cluster.Kind for RoomEventProcessor
func GetRoomEventProcessorKind(opts ...actor.PropsOption) *cluster.Kind {
	props := actor.PropsFromProducer(func() actor.Actor {
		return &RoomEventProcessorActor{
			Timeout: 60 * time.Second,
		}
	}, opts...)
	kind := cluster.NewKind("RoomEventProcessor", props)
	return kind
}

// GetRoomEventProcessorKind instantiates a new cluster.Kind for RoomEventProcessor
func NewRoomEventProcessorKind(factory func() RoomEventProcessor, timeout time.Duration, opts ...actor.PropsOption) *cluster.Kind {
	xRoomEventProcessorFactory = factory
	props := actor.PropsFromProducer(func() actor.Actor {
		return &RoomEventProcessorActor{
			Timeout: timeout,
		}
	}, opts...)
	kind := cluster.NewKind("RoomEventProcessor", props)
	return kind
}

// RoomEventProcessor interfaces the services available to the RoomEventProcessor
type RoomEventProcessor interface {
	Init(ctx cluster.GrainContext)
	Terminate(ctx cluster.GrainContext)
	ReceiveDefault(ctx cluster.GrainContext)
	SetupRoom(req *SetupRoomRequest, ctx cluster.GrainContext) (*SetupRoomResponse, error)
}

// RoomEventProcessorGrainClient holds the base data for the RoomEventProcessorGrain
type RoomEventProcessorGrainClient struct {
	Identity string
	cluster  *cluster.Cluster
}

// SetupRoom requests the execution on to the cluster with CallOptions
func (g *RoomEventProcessorGrainClient) SetupRoom(r *SetupRoomRequest, opts ...cluster.GrainCallOption) (*SetupRoomResponse, error) {
	if g.cluster.Config.RequestLog {
		g.cluster.Logger().Info("Requesting", slog.String("identity", g.Identity), slog.String("kind", "RoomEventProcessor"), slog.String("method", "SetupRoom"), slog.Any("request", r))
	}
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 0, MessageData: bytes}
	resp, err := g.cluster.Request(g.Identity, "RoomEventProcessor", reqMsg, opts...)
	if err != nil {
		return nil, fmt.Errorf("error request: %w", err)
	}
	switch msg := resp.(type) {
	case *SetupRoomResponse:
		return msg, nil
	case *cluster.GrainErrorResponse:
		if msg == nil {
			return nil, nil
		}
		return nil, msg
	default:
		return nil, fmt.Errorf("unknown response type %T", resp)
	}
}

// RoomEventProcessorActor represents the actor structure
type RoomEventProcessorActor struct {
	ctx     cluster.GrainContext
	inner   RoomEventProcessor
	Timeout time.Duration
}

// Receive ensures the lifecycle of the actor for the received message
func (a *RoomEventProcessorActor) Receive(ctx actor.Context) {
	switch msg := ctx.Message().(type) {
	case *actor.Started: //pass
	case *cluster.ClusterInit:
		a.ctx = cluster.NewGrainContext(ctx, msg.Identity, msg.Cluster)
		a.inner = xRoomEventProcessorFactory()
		a.inner.Init(a.ctx)

		if a.Timeout > 0 {
			ctx.SetReceiveTimeout(a.Timeout)
		}
	case *actor.ReceiveTimeout:
		ctx.Poison(ctx.Self())
	case *actor.Stopped:
		a.inner.Terminate(a.ctx)
	case actor.AutoReceiveMessage: // pass
	case actor.SystemMessage: // pass

	case *cluster.GrainRequest:
		switch msg.MethodIndex {
		case 0:
			req := &SetupRoomRequest{}
			err := proto.Unmarshal(msg.MessageData, req)
			if err != nil {
				ctx.Logger().Error("[Grain] SetupRoom(SetupRoomRequest) proto.Unmarshal failed.", slog.Any("error", err))
				resp := cluster.NewGrainErrorResponse(cluster.ErrorReason_INVALID_ARGUMENT, err.Error()).
					WithMetadata(map[string]string{
						"argument": req.String(),
					})
				ctx.Respond(resp)
				return
			}

			r0, err := a.inner.SetupRoom(req, a.ctx)
			if err != nil {
				resp := cluster.FromError(err)
				ctx.Respond(resp)
				return
			}
			ctx.Respond(r0)
		}
	default:
		a.inner.ReceiveDefault(a.ctx)
	}
}

// onError should be used in ctx.ReenterAfter
// you can just return error in reenterable method for other errors
func (a *RoomEventProcessorActor) onError(err error) {
	resp := cluster.FromError(err)
	a.ctx.Respond(resp)
}

func respond[T proto.Message](ctx cluster.GrainContext) func(T) {
	return func(resp T) {
		ctx.Respond(resp)
	}
}
