// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: room_actor.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetupRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	QueuePfx      string                 `protobuf:"bytes,2,opt,name=queuePfx,proto3" json:"queuePfx,omitempty"`
	QueueRef      string                 `protobuf:"bytes,3,opt,name=queueRef,proto3" json:"queueRef,omitempty"`
	QueueUri      string                 `protobuf:"bytes,4,opt,name=queueUri,proto3" json:"queueUri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupRoomRequest) Reset() {
	*x = SetupRoomRequest{}
	mi := &file_room_actor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupRoomRequest) ProtoMessage() {}

func (x *SetupRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_actor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupRoomRequest.ProtoReflect.Descriptor instead.
func (*SetupRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_actor_proto_rawDescGZIP(), []int{0}
}

func (x *SetupRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SetupRoomRequest) GetQueuePfx() string {
	if x != nil {
		return x.QueuePfx
	}
	return ""
}

func (x *SetupRoomRequest) GetQueueRef() string {
	if x != nil {
		return x.QueueRef
	}
	return ""
}

func (x *SetupRoomRequest) GetQueueUri() string {
	if x != nil {
		return x.QueueUri
	}
	return ""
}

type SetupRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupRoomResponse) Reset() {
	*x = SetupRoomResponse{}
	mi := &file_room_actor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupRoomResponse) ProtoMessage() {}

func (x *SetupRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_actor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupRoomResponse.ProtoReflect.Descriptor instead.
func (*SetupRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_actor_proto_rawDescGZIP(), []int{1}
}

func (x *SetupRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetupRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ActorStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorStarted) Reset() {
	*x = ActorStarted{}
	mi := &file_room_actor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorStarted) ProtoMessage() {}

func (x *ActorStarted) ProtoReflect() protoreflect.Message {
	mi := &file_room_actor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorStarted.ProtoReflect.Descriptor instead.
func (*ActorStarted) Descriptor() ([]byte, []int) {
	return file_room_actor_proto_rawDescGZIP(), []int{2}
}

func (x *ActorStarted) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type ActorStopped struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorStopped) Reset() {
	*x = ActorStopped{}
	mi := &file_room_actor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorStopped) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorStopped) ProtoMessage() {}

func (x *ActorStopped) ProtoReflect() protoreflect.Message {
	mi := &file_room_actor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorStopped.ProtoReflect.Descriptor instead.
func (*ActorStopped) Descriptor() ([]byte, []int) {
	return file_room_actor_proto_rawDescGZIP(), []int{3}
}

func (x *ActorStopped) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type WorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkRequest) Reset() {
	*x = WorkRequest{}
	mi := &file_room_actor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkRequest) ProtoMessage() {}

func (x *WorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_actor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkRequest.ProtoReflect.Descriptor instead.
func (*WorkRequest) Descriptor() ([]byte, []int) {
	return file_room_actor_proto_rawDescGZIP(), []int{4}
}

func (x *WorkRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

var File_room_actor_proto protoreflect.FileDescriptor

const file_room_actor_proto_rawDesc = "" +
	"\n" +
	"\x10room_actor.proto\x12\x05actor\"~\n" +
	"\x10SetupRoomRequest\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12\x1a\n" +
	"\bqueuePfx\x18\x02 \x01(\tR\bqueuePfx\x12\x1a\n" +
	"\bqueueRef\x18\x03 \x01(\tR\bqueueRef\x12\x1a\n" +
	"\bqueueUri\x18\x04 \x01(\tR\bqueueUri\"G\n" +
	"\x11SetupRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"&\n" +
	"\fActorStarted\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\"&\n" +
	"\fActorStopped\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\"%\n" +
	"\vWorkRequest\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId2V\n" +
	"\x12RoomEventProcessor\x12@\n" +
	"\tSetupRoom\x12\x17.actor.SetupRoomRequest\x1a\x18.actor.SetupRoomResponse\"\x00B|\n" +
	"\tcom.actorB\x0eRoomActorProtoP\x01Z+github.com/antinvestor/matrix/apis/actor/v1\xa2\x02\x03AXX\xaa\x02\x05Actor\xca\x02\x05Actor\xe2\x02\x11Actor\\GPBMetadata\xea\x02\x05Actorb\x06proto3"

var (
	file_room_actor_proto_rawDescOnce sync.Once
	file_room_actor_proto_rawDescData []byte
)

func file_room_actor_proto_rawDescGZIP() []byte {
	file_room_actor_proto_rawDescOnce.Do(func() {
		file_room_actor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_actor_proto_rawDesc), len(file_room_actor_proto_rawDesc)))
	})
	return file_room_actor_proto_rawDescData
}

var file_room_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_room_actor_proto_goTypes = []any{
	(*SetupRoomRequest)(nil),  // 0: actor.SetupRoomRequest
	(*SetupRoomResponse)(nil), // 1: actor.SetupRoomResponse
	(*ActorStarted)(nil),      // 2: actor.ActorStarted
	(*ActorStopped)(nil),      // 3: actor.ActorStopped
	(*WorkRequest)(nil),       // 4: actor.WorkRequest
}
var file_room_actor_proto_depIdxs = []int32{
	0, // 0: actor.RoomEventProcessor.SetupRoom:input_type -> actor.SetupRoomRequest
	1, // 1: actor.RoomEventProcessor.SetupRoom:output_type -> actor.SetupRoomResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_room_actor_proto_init() }
func file_room_actor_proto_init() {
	if File_room_actor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_actor_proto_rawDesc), len(file_room_actor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_actor_proto_goTypes,
		DependencyIndexes: file_room_actor_proto_depIdxs,
		MessageInfos:      file_room_actor_proto_msgTypes,
	}.Build()
	File_room_actor_proto = out.File
	file_room_actor_proto_goTypes = nil
	file_room_actor_proto_depIdxs = nil
}
