services:
  datastore:
    hostname: datastore
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: s3cr3t
      POSTGRES_USER: matrix
      POSTGRES_DATABASE: matrix
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U matrix" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal
    ports:
      - 5432:5432

  matrix:
    hostname: matrix
    build: .
    ports:
      - 8008:8008
      - 8448:8448
    depends_on:
      datastore:
        condition: service_healthy
    networks:
      - internal
    restart: unless-stopped
    volumes:
      - ./runtime/config:/etc/matrix

networks:
  internal:
    attachable: true
