services:
  datastore:
    hostname: datastore
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: s3cr3t
      POSTGRES_USER: dendrite
      POSTGRES_DATABASE: dendrite
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dendrite" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

  matrix:
    hostname: matrix
    build: .
    ports:
      - 8008:8008
      - 8448:8448
    depends_on:
      datastore:
        condition: service_healthy
    networks:
      - internal
    restart: unless-stopped
    volumes:
      - ./sample-matrix.yaml:/etc/matrix/matrix.yaml

networks:
  internal:
    attachable: true
