# Based on https://github.com/docker/build-push-action

name: "Test Images Release"

on:

  workflow_dispatch: # A build was manually requested

jobs:
  monolith:
    name: Test dependancy images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write # To upload Trivy sarif files
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push to Github Container Registry
      - name: Build and Pushing Image to Github Container Registry
        uses: docker/build-push-action@v6
        with:
          context: ./build/scripts
          file: {context}/Redis.Dockerfile
          push: true
          tags: antinvestor/redis:latest
