# Based on https://github.com/docker/build-push-action

name: "Build redis image"

on:
  workflow_dispatch: # A build was manually requested

jobs:
  redis:
    name: Redis image build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Pushing Image to Github Container Registry
        uses: docker/build-push-action@v6
        with:
          file: Redis.Dockerfile
          push: true
          tags: ghcr.io/antinvestor/redis:latest
